"""
Generate GROMACS index file (atoms.ndx) and LAMMPS group file based on role mapping.
"""
import logging
from pathlib import Path
from typing import Dict, List, Optional

from models import PackedSystem

logger = logging.getLogger(__name__)

def write_atoms_ndx(system: PackedSystem, output_path: Path) -> bool:
    """
    Generate GROMACS/PLUMED compatible index file atoms.ndx.
    
    Format:
        [ group_name ]
        1 2 3 4 ...
    
    Maximum 15 atom IDs per line, automatic line wrapping.
    
    Args:
        system: Packed system
        output_path: Output file path
    
    Returns:
        True if successful
    """
    try:
        # Collect atom IDs by role
        role_to_ids: Dict[str, List[int]] = {}
        for atom in system.atoms:
            role_to_ids.setdefault(atom.role, []).append(atom.global_id)
        
        # Collect by template name
        template_to_ids: Dict[str, List[int]] = {}
        for atom in system.atoms:
            template_to_ids.setdefault(atom.template_name, []).append(atom.global_id)
        
        # Add global group
        all_ids = [atom.global_id for atom in system.atoms]
        
        with open(output_path, 'w') as f:
            f.write("# GROMACS index file generated by SmilesToLammps\n")
            f.write("# Groups: roles, molecule types, and element groups for CVHD\n\n")
            
            # All group
            f.write("[ All ]\n")
            _write_ids_line(f, all_ids)
            f.write("\n")
            
            # 每个角色组
            for role in sorted(role_to_ids.keys()):
                f.write(f"[ {role} ]\n")
                _write_ids_line(f, role_to_ids[role])
                f.write("\n")
            
            # CVHD 必需的元素组合组
            # 收集元素类型分组
            element_groups = {
                "h_all": [atom.global_id for atom in system.atoms if atom.element == "H"],
                "c_all": [atom.global_id for atom in system.atoms if atom.element == "C"],
                "o_all": [atom.global_id for atom in system.atoms if atom.element == "O"],
                "n_all": [atom.global_id for atom in system.atoms if atom.element == "N"],
                "heavy_all": [atom.global_id for atom in system.atoms if atom.element not in ["H"]],
            }
            
            # 写入元素组合组
            for group_name, ids in element_groups.items():
                if ids:  # 只写入非空组
                    f.write(f"[ {group_name} ]\n")
                    _write_ids_line(f, ids)
                    f.write("\n")
            
            # 每个模板组
            for tname in sorted(template_to_ids.keys()):
                f.write(f"[ {tname} ]\n")
                _write_ids_line(f, template_to_ids[tname])
                f.write("\n")
            
            # 可选：按分子 ID 分组（不单独写入，太大）
        
        logger.info(f"Wrote atoms.ndx to {output_path}")
        return True
    except Exception as e:
        logger.exception(f"Failed to write atoms.ndx: {e}")
        return False

def write_lammps_groups(system: PackedSystem, output_path: Path) -> bool:
    """
    生成 LAMMPS group 命令文件（例如 groups.lmp）。
    
    格式：
        group group_name id 1 2 3 ...
        或
        group group_name id 1:100 200 300:400
    
    自动合并连续 ID 为区间表示法以节省空间。
    
    Args:
        system: 打包后的体系
        output_path: 输出文件路径
    
    Returns:
        成功返回 True
    """
    try:
        # 按角色收集原子 ID
        role_to_ids: Dict[str, List[int]] = {}
        for atom in system.atoms:
            role_to_ids.setdefault(atom.role, []).append(atom.global_id)
        
        # 按模板收集
        template_to_ids: Dict[str, List[int]] = {}
        for atom in system.atoms:
            template_to_ids.setdefault(atom.template_name, []).append(atom.global_id)
        
        with open(output_path, 'w') as f:
            f.write("# LAMMPS group commands generated by SmilesToLammps\n")
            f.write("# Each line defines a group by ID list or range.\n")
            f.write("# Usage: include this file in your LAMMPS input via 'include groups.lmp'\n\n")
            
            # 全组
            all_ids = [atom.global_id for atom in system.atoms]
            f.write(f"group All id {_format_id_range(all_ids)}\n")
            
            # 角色组
            for role in sorted(role_to_ids.keys()):
                ids = role_to_ids[role]
                f.write(f"group {role} id {_format_id_range(ids)}\n")
            
            # CVHD 必需的元素组合组
            # 收集元素类型分组
            element_groups = {
                "h_all": [atom.global_id for atom in system.atoms if atom.element == "H"],
                "c_all": [atom.global_id for atom in system.atoms if atom.element == "C"],
                "o_all": [atom.global_id for atom in system.atoms if atom.element == "O"],
                "n_all": [atom.global_id for atom in system.atoms if atom.element == "N"],
                "heavy_all": [atom.global_id for atom in system.atoms if atom.element not in ["H"]],
            }
            
            # 写入元素组合组
            for group_name, ids in element_groups.items():
                if ids:  # 只写入非空组
                    f.write(f"group {group_name} id {_format_id_range(ids)}\n")
            
            # 模板组
            for tname in sorted(template_to_ids.keys()):
                ids = template_to_ids[tname]
                f.write(f"group {tname} id {_format_id_range(ids)}\n")
        
        logger.info(f"Wrote LAMMPS groups to {output_path}")
        return True
    except Exception as e:
        logger.exception(f"Failed to write LAMMPS groups: {e}")
        return False

def _format_id_range(ids: List[int]) -> str:
    """
    将整数列表转换为 LAMMPS 可接受的 ID 范围表示法。
    例如 [1,2,3,5,6,7,9] -> "1:3 5:7 9"
    """
    if not ids:
        return ""
    ids_sorted = sorted(set(ids))
    ranges = []
    start = ids_sorted[0]
    end = start
    for i in range(1, len(ids_sorted)):
        if ids_sorted[i] == end + 1:
            end = ids_sorted[i]
        else:
            if start == end:
                ranges.append(str(start))
            else:
                ranges.append(f"{start}:{end}")
            start = end = ids_sorted[i]
    # 最后一段
    if start == end:
        ranges.append(str(start))
    else:
        ranges.append(f"{start}:{end}")
    return " ".join(ranges)

def _write_ids_line(file, ids: List[int], max_per_line: int = 15):
    """写入索引文件中的 ID 列表，每行最多 max_per_line 个 ID"""
    for i in range(0, len(ids), max_per_line):
        chunk = ids[i:i+max_per_line]
        file.write(" " + " ".join(str(x) for x in chunk) + "\n")